### ISSUE TITLE
Fix product category relationship

### ISSUE THREAD

**Issue by hajoeichler** [sphereio/sphere-sunrise-data#12]
- [x] There are a lot of products without a reference to categories.
- [x] Some products need to be in the sales categories
- [x] Some products need to be in the NEW categories

**Comment by hajoeichler** [comment]
Additionally we have to add a product discount predicate that works together with the products that are in the sales category. This predicate should not contain any internal IDs.

**Comment by trangng** [comment]
@hajoeichler tried to create the product discount with categories.id contains but it doesn't work. 
categories.id contains "cfedbda7-55cf-4c1e-9e35-1378a0418c64"
I get the error message: What you've entered is not valid.

**Comment by hajoeichler** [comment]
I added a discount in sunrise-staging
