### ISSUE TITLE
Provide category description

### ISSUE THREAD

**Issue by hajoeichler** [sphereio/sphere-sunrise-data#15]

**Comment by schleichardt** [comment]
Duplicate? https://github.com/sphereio/sphere-sunrise-data/issues/16

**Comment by lauraluiz** [comment]
Hahaha sorry, I added in case @hajoeichler would forget it. I see he was faster :P

**Comment by trangng** [comment]
@hajo here is the csv for the categories

**Comment by trangng** [comment]
@hajoeichler I added the categories here: https://github.com/sphereio/sphere-sunrise-data/blob/master/categories/sunrise-categories_with_description.csv

**Comment by trangng** [comment]
category descriptions are provided and in MC already
