### ISSUE TITLE
Remove empty categories

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-sunrise-data#17]
- [x] Women/Shoes/Boots
- [x] Women/Shoes/Lace-Up Shoes
- [x] Women/Bags/Bucketbag & Packback
- [x] Women/Looks (not even accessible right now)
- [x] Men/Bags (and subcategories)
- [x] Men/Shoes/Boots
- [x] Men/Shoes/Sandals
- [x] Men/Looks (not even accessible right now)
- [x] Accessories/Women/Shoes
- [x] Accessories/Women/Bags
- [x] Accessories/Men/Sunglasses
- [x] Brands
- [x] New/Women/Looks
- [x] New/Men/Bags
- [x] New/Men/Looks
- [x] New/Special (and subcategories)

**Comment by lauraluiz** [comment]
- [ ] Women/Shoes/Boots
- [ ] Women/Shoes/Lace-Up Shoes
- [ ] Women/Bags/Bucketbag & Packback
- [ ] Women/Looks (not even accessible right now)
- [ ] Men/Bags (and subcategories)
- [ ] Men/Shoes/Boots
- [ ] Men/Shoes/Sandals
- [ ] Men/Looks (not even accessible right now)
- [ ] Accessories/Women/Shoes
- [ ] Accessories/Women/Bags
- [ ] Accessories/Men/Sunglasses
- [ ] Brands
- [ ] New/Women/Looks
- [ ] New/Men/Bags
- [ ] New/Men/Looks
- [ ] New/Special (and subcategories)

**Comment by trangng** [comment]
all empty categories are removed
