### ISSUE TITLE
remove some prices out of the product

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-sunrise-data#5]

**Comment by schleichardt** [comment]
@lauraluiz  which prices should be removed or kept?

**Comment by lauraluiz** [comment]
We should remove every country we are not supporting, as now it feels we are having have of the world there. It really kills performance without the price improvements in the platform.

**Comment by schleichardt** [comment]
What are the countries we are supporting?

**Comment by trangng** [comment]
@lauraluiz @schleichardt if I can support you please let me know. 
At the moment we have DE, US, FR, IT and ES. I could remove FR, IT and ES.

**Comment by lauraluiz** [comment]
@schleichardt @trangng we support those countries, but our data is holding 28 countries per variant. So yes, we have to remove these additional countries that we do not officially support. 5 countries in total should be fine.

**Comment by trangng** [comment]
@lauraluiz ok we can remove it manually or are there other faster ways?

**Comment by schleichardt** [comment]
I think I can remove it very fast.

**Comment by hajoeichler** [comment]
For now we keep GB, IT and DE + the price without country.

**Comment by hajoeichler** [comment]
done in f8b7198a6631c0cda9a6290a4adfcb60e6ec4615.
