### ISSUE TITLE
the products don't have a tax category assigned so they cannot added to a cart

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-sunrise-data#6]

**Comment by schleichardt** [comment]
I added manually the tax category to https://admin.sphere.io/sunrise-staging/products/9c0c31c6-3c9c-44a5-b70d-3403d62c9039/overview

**Comment by schleichardt** [comment]
and to https://admin.sphere.io/sunrise-staging/products/68fe44d6-e936-42ad-ae89-5e368a313082

**Comment by hajoeichler** [comment]
Fixed in 86cf9f56a25821a1ac7de02ed4facfff00a9c5d8.
